# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f219961dbbce8352b8f2393031fa8a3025b946ba1c3a07f64c054b7857c541ea49ea957bd22e61a6f3356a180c168e0f4c571bc62acbf3f93777b686397b6bd

test:
  secret_key_base: 24cd53716935e9993767a4e8207872d360bf6607afeb50c2ddd93d11982bb5812515fe682d32788314d73585216449bc822e6f6ff871c309db580139f30da3c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
